### ISSUE TITLE
Mono.Cecil bug (no idea why)

### ISSUE THREAD

**Issue by SomeCatIDK** [RocketMod/Rocket.Eco#12]
This exception only happens when attempting to run `AssemblyDefinition.Write` on the `Eco.Core` assembly.
```
Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve System.Reflection.BindingFlags
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Rocket.Eco.Launcher.Program.LoadAssemblyFromDefinition(AssemblyDefinition definition)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Rocket.Eco.Launcher.Program.Main(String[] args)
```

**Comment by SomeCatIDK** [comment]
Fixed, no thanks to fucking Mono.Cecil.
